services:
  api-rest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-rest
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped